modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"

[[mods]]
modId="traincraft"
version="5.0.0-alpha1"
displayName="Traincraft"
description="A mod that adds trains, rolling stock, and railway systems to Minecraft."
authors="Spitfire4466, Mrbrutal, canitzp, NitroxydeX"
credits="Original mod by Spitfire4466 & Mrbrutal"
homepage="https://github.com/TheFirstIstari/Traincraft"
displayURL="https://github.com/TheFirstIstari/Traincraft"
#logoFile="logo.png"

[[dependencies.traincraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"

[[dependencies.traincraft]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,21.2)"
    ordering="AFTER"